### PR TITLE
Accelerated Mobile Pages Support and Intergration

### PR DESCRIPTION
**Pull request by koconder**
Initial basic/experimental build that supports AMP pages by automatic. Tested and working, further testing needs to be conducted around 3rd party and AMP specific rules to further extend functionality.

Linked to issues:
#45 (https://github.com/duracelltomi/gtm4wp/issues/45)

And other github queries:
https://github.com/Automattic/amp-wp/issues/908
https://github.com/Automattic/amp-wp/pull/1143

### CODE REVIEW

**Comment by duracelltomi** [comment]
Thanks for this addition!

I've just released v1.8, some days needs to be passed before I can review your codes and add it to the core.

**Comment by koconder** [comment]
Thanks @duracelltomi once the initial version is out, ill keep it updated from the AMP side of things to improve over time with AMP related features and feedback

**Comment by koconder** [comment]
Did some additional tests on AMP integration and pushed an additional commit to support.

**Comment by duracelltomi** [comment]
Hi @koconder 

I really appreciate your work, it is fantastic to see your contribution to this plugin.
Please give me some days to review your codes, I would like to make sure this gets added to the core as soon as possible.

**Comment by koconder** [comment]
@duracelltomi i've just been doing some additional changes. Once you are happy, please do test thoroughly we can merge. Then i can do some additional clean-ups and features on the AMP side once i have it working properly. I have a few things in mind for the AMP side of things but best to build it up slowly.

**Comment by duracelltomi** [comment]
I wonder why you choose to store the content of the generated data layer into `$gtm4wp_options[ GTM4WP_OPTION_INTEGRATE_AMPCODE_DATALAYER ]` ?

$gtm4wp_options is used to store plugin settings, not for any temporal data storage.

What would be the purpose of those plugin options?
GTM4WP_OPTION_INTEGRATE_AMPID_INJECTED
GTM4WP_OPTION_INTEGRATE_AMPCODE_AMP
GTM4WP_OPTION_INTEGRATE_AMPCODE_GTM

**Comment by koconder** [comment]
@duracelltomi i needed a quick way to pass data between the functions, was using it as a comtained global space, let me know if you want me to refactor it at all in any particular way. I also need a variable to store if AMP injection has occured as its designed to later work with other amp plugins

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by duracelltomi** [comment]
If you look at the top of integration/woocommerce.php I use some global variables with the gtm4wp_ prefix to store such data. I know this is not the fanciest way but at this point I would be happy if we could follow this structure instead of using gtm4wp_options

**Comment by koconder** [comment]
@duracelltomi any updates on reviewing this PR, i have a number of other changes which i cant do till i have this PR merged

**Comment by duracelltomi** [comment]
I've released v1.8.1 yesterday, will wait 1-2 days to see whether there are any issues - after this I (we) will focus on building v1.9 starting with this PR

**Comment by glenngabe** [comment]
@koconder Hey, so this would resolve the issue I mentioned in my thread about adding GTM support for the AMP plugin? That would be INCREDIBLE. When is that being released? Thanks for your help!

**Comment by duracelltomi** [comment]
There is currently no ETA for the next plugin version release.
I have still lots of todos on the list. I would say not before middle of July for sure.

**Comment by koconder** [comment]
Heads up i requested the use of #116 within the official AMP plugin https://github.com/ampproject/amp-wp/pull/1143

**Pull request merged**
