### PR TITLE
Dannyvan holten patch 1

### PR DESCRIPTION
**Pull request by DannyvanHolten**

### CODE REVIEW

**Comment by DannyvanHolten** [comment]
This is actually only for the frontend.php changes.

**Comment by duracelltomi** [comment]
You've changed the type attribute of the <script> tag from "text/javascript" to "javascript".
Could you please explain why?

**Comment by DannyvanHolten** [comment]
Sorry for the late comment. Because in my website, werkenbijzwolle.nl it rendered some anchors useless because of that. I don't know why exactly, but this is wat fixed it.

**Comment by duracelltomi** [comment]
Could you let me know the URL of your website?
That seems to me as some bug.

Honestly (as always) I do not intend to let this <script> tag change into the plugin as it is not how it should work.

Also: you have another pull request where you've added the changes of admin.php as well, should I ignore that one and only use this pull request?

**Pull request closed without merging**
