### PR TITLE
Ready to Merge - CI Fixes

### PR DESCRIPTION
**Pull request by koconder**
Number of fixes for CI based on my fork which is maintained here: https://github.com/koconder/wordpress-test-template

Updates on the testing suite:
* Full PHP Nightly, HHVM, and >=5.4 upto 7.3
* Multisite Support
* Travis CI Fixed
* PHP Coding Standards
* Coveralls and PHP Coverages Checks
* Docker Support via a secondary repo for testing

Changes to this repo via this PR:
* Porting fixes for Travis CI configuration
* Using install scripts maintained at https://github.com/koconder/wordpress-test-template for Wordpress tests and configuration
* Auto-patches from Scrutinizer CI
* Auto-patches from PHPCS for Wordpress Coding Standards
* Patched composer.json licence to pass tests

Please note for testing purposes this PR includes as rebase of #104 to avoid merge conflicts

### CODE REVIEW

**Comment by duracelltomi** [comment]
I am just releasing v1.9.1, after that, I will get back to this PR as well

**Comment by duracelltomi** [comment]
Hi,

Just a last question before committing this: lots of files have been changed, in most cases the usage of whitespace has been altered. Many times I see the why, sometimes not: I use quite often multiple spaces to align the equality mark where some variable declarations are added. Maybe this is just part of a coding standard a was not aware yet :-) I am just curious about that.

**Comment by koconder** [comment]
@duracelltomi sorry for the late reply, Wordpress has its own coding standards which you can read here:

- https://codex.wordpress.org/WordPress_Coding_Standards
- https://www.smashingmagazine.com/2012/07/guide-wordpress-coding-standards/
- https://www.elegantthemes.com/blog/resources/a-newbies-guide-to-wordpress-coding-standards

And we check in CI using PHPCS with the correct setup for Wordpress:
- https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

I'll also add a commit to support Editor configuration, so the code is auto adjusted depending on your editor https://editorconfig.org/

**Comment by koconder** [comment]
@duracelltomi added the editorconfigs, depending on your editor JS, CSS, PHP should all automatically aim to conform to the Wordpress Standards

**Comment by duracelltomi** [comment]
Thanks, I was trying to use the WP coding standard but obviously not on all lines :-)

**Pull request merged**
