### PR TITLE
Fix GA data being dropped due to 8kb limit for product impression data

### PR DESCRIPTION
**Pull request by zookatron**
Google Analytics has an 8kb request size limit on tracking data requests, and if a page has too many WooCommerce products displayed on it, it will exceed the packet size limit due to all the product impression data that is added to the singe dataLayer event. Apparently when this happens there is no warnings from GA of any kind, the packet is simply not sent. We only noticed this because we had a sudden sharp loss in page views when we added some extra products to our shop page.

This can be addressed by splitting the product impression data into multiple events, such that each one is below the limit. I've been forced to patch the plugin manually on our site with the change contained in this pull request but it would be great if we could have a fix for this added to the next update to the plugin.

Note that this change introduces the new "gtm4wp.addImpressions" GTM event for submitting the impression data chunks.

### CODE REVIEW

**Comment by zookatron** [comment]
Thanks, I'm currently running this code on our website, but that's been the extent of my testing. I noticed there were some config files for automated tests in the repo but it doesn't look like they've been built out yet. Let me know if there's anything else I should do to move this pull request along.

**Comment by koconder** [comment]
@zookatron the automated tests (unit tests) don't go as far as testing the analytics behaviour. Mostly testing and ensuring it wont break Wordpress. I'm a contributor to this plugin and @duracelltomi is the only one that can approve your PR

**Comment by duracelltomi** [comment]
Hi Everyone :-)

I was in connection with @zookatron  via email and asked him to add his code using a PR as this feature was planned by me earlier but not on the top1 place "on the list" :-)

I you do not mind Tim, after merging the PR I will add some more code to your solution since after releasing this into a new plugin version would immediately break every GTM implementation as people will need to add an extra event to their ecommerce events trigger.

I will make this feature an option so that everyone has the time to upgrade and in a future version of the plugin this will become the default behavior.

**Comment by zookatron** [comment]
Hi @duracelltomi, that sounds good, I totally understand having it as an option so it doesn't break existing installs. Thanks for merging this in, I look forward to the next update that includes this functionality!

**Comment by duracelltomi** [comment]
@zookatron  you will need to update your GTM triggers once this change goes live:
https://github.com/duracelltomi/gtm4wp/commit/c543be000a2eed89a7d32c9b1b8faf43f5ce5022

**Comment by duracelltomi** [comment]
Done:
https://gtm4wp.com/how-to-articles/how-to-setup-enhanced-ecommerce-tracking

Changelog includes now a warning as well:
https://github.com/duracelltomi/gtm4wp/commit/cdb824232a862191ddd5aa2a87fc66b77846d10c

**Pull request merged**
