### PR TITLE
Visitor IP

### PR DESCRIPTION
**Pull request by tijevlam**
Hi Thomas,

I took the liberty to propose a new branch including the remote ip option in the backend and pushing into the frontend. I do not have complete insights in your codebase, so please do check carefully.

### CODE REVIEW

**Comment by tijevlam** [comment]
Hi @duracelltomi see #60 for my reply in the discussion.
TLDR; I've made the changes you suggested.

**Comment by tijevlam** [comment]
@duracelltomi, any chance youve been able to have a second look at this updated PR?

**Comment by duracelltomi** [comment]
Hi,

A new bug has been identified in v1.8, fix is being tested within some testers currently. Our goal is to release v1.8.1 on Monday. Until then, we will need to wait with new PRs.

Also I was quite busy with GDPR related GTM setups, I hope you understand that.

Thanks for your patience!

**Comment by tijevlam** [comment]
Hi,

Offcourse i understand that. All of us are familiar with the GDPR madness 😁. 

That was just the thing. This visitor IP could me help with GDPR friendly filtering thats why i was nagging, im sorry. 

I get that bugs need to be fix first. Thanks for your update!

@koconder, is there any way i could try my branch on an own local site?

**Pull request merged**
