### PR TITLE
Revised readme further

### PR DESCRIPTION
**Pull request by henkisdabro**
Mostly minor corrections, but some additional clarity added to some sections. This time, I hope the diffs are maintained.

### CODE REVIEW

**Comment by duracelltomi** [comment]
"Data is fetched from the WhichBrowser" - this is not correct, the library is included in the plugin itself and not used like the geoip service for weather tracking.

In the scroll tracking section: "Google Tag Manager does not have tracking features in itself" - this is not true as GTM has now the native scroll tracking trigger but it behaves differently as the solution in my plugin (GTM: % tracking, GTM4WP: content top-bottom tracking)

**Comment by henkisdabro** [comment]
Apologies for the misunderstanding with Whichbrowser, now corrected.

I have also revised the section with scroll tracking. I think we are battling a difference in definition of "tracking" - we both mean the same thing, but tracking can be interpreted as collecting data such as google analytics - in this context, GTM does not "track/collect" data, but helps facilitate firing "tracking" tags. 

No problems, I see what you mean, hope the changes make sense :-)

**Comment by henkisdabro** [comment]
Just checking, is the Travis CI enabled on your repo, which is why I am seeing the checks here? What do I do with these?

image

**Comment by duracelltomi** [comment]
Thanks @henkisdabro!

I still try to understand the basic concepts of Travis-CI, this is why you see this error message. You can simply ignore it :-)

**Pull request merged**
