### PR TITLE
Patching WooCommerce JS Fixes

### PR DESCRIPTION
**Pull request by koconder**
Fixing issues from #34 which was causing some JS to be pipped out to the pages.

### CODE REVIEW

**Comment by koconder** [comment]
@duracelltomi will review your comments and resolve/respond in the next 24 hours or so with updates.

**Comment by koconder** [comment]
@duracelltomi i see what you mean now, so the WC checks and loading are all hooked in. as per your last point. We would need to find a way to stop the "echoing" in the do_action. One though is using ob_start and output buffering to pull into a variable but i think that might cause some nightmares.

I might change into a global function call that can pull the variables through, instead of do_action but keeping within the WC setup. I'll have a stab at cleaning this up.

**Comment by duracelltomi** [comment]
I think we should keep your approach to change `do_action()` to `apply_filters()` but nothing more has to be changed: no need to change the value of the corresponding constant, no need to check for `WC()` before calling `apply_filters()`

**Comment by koconder** [comment]
Agreed, ill get that sorted in the next 24hours. Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by koconder** [comment]
@duracelltomi fixes applied to your initial work, two things:

1. Rolled back the changes to the hooks, and moved to apply_filters and add_filter to make this extendible. The filter function was setup in a way where variables in HTML form can be passed as well as a function name, which is hooking to the WC global variables. - Added PHPDoc documentation to support. This fixes the JS issues where the JS was spitting outside of the $_gtm variables which need to be suppressed for other plugin intergrations like AMP, thus removing do_action.

2. Issues where later found in testing, where there was in the Woo intergration using (bool), in some cases where these were "false" in PHP false = empty. Added a function in the frontend.php `gtm4wp_escjs_boolean` to convert empty JS variables to `false`. See examples:

Before: https://imgur.com/a/EXJXknM
After: https://imgur.com/a/Wz0EjrG

Feel free to test, this should resolve the JS and WP issues caused from the recent WC refactoring part of #34

**Comment by duracelltomi** [comment]
Thanks for the great work!

**Pull request merged**
