### PR TITLE
Cleaning JS files for Cross-Browser and Compatibility Issues

### PR DESCRIPTION
**Pull request by koconder**
Part of #68 and #34

### CODE REVIEW

**Comment by koconder** [comment]
Need to test against #83

**Comment by duracelltomi** [comment]
Thanks for this work as well. Could you explain why the change in admin-tabcreator.js, line 12 was necessary?

I put ; endings into most .js beginning and ending as some other authors sometimes miss this at the end of other .js files and while those .js files were merged into a single .js file by a cache plugin, things broke. Do you think this is not necessary anymore?

gtm4wp-social-tracker.js will be removed soon, especially Twitter's code can conflict with other plugins if loaded multiple times by multiple plugins.

**Comment by koconder** [comment]
@duracelltomi will review your comments and resolve/respond in the next 24 hours or so with updates.

**Comment by koconder** [comment]
@duracelltomi i have rolled back the change on the admintabs line 12, the rest is to pass JS validation. As you started cleaning the WC js codebase i thought it was fitting.

Keeping the ; is likely to cause more problems than we expect. Social tracker yes, i see how there could be conflicts with the object calls. I have just cleaned up and tested where possible and kept functionality the same. Its more for IE and some non-modern browsers it could cause havoc with and also some JS compression tools.

Should be good to merge now with that extra change added.

**Pull request merged**
