### PR TITLE
Simplifications, spelling/grammar corrections to readme file

### PR DESCRIPTION
**Pull request by henkisdabro**
Attempted to help clarify some parts of the text, rewrite a few sentences to flow better and add spelling and grammar improvements. Feel free to revise and reject wherever you see fit. :-)

### CODE REVIEW

**Comment by henkisdabro** [comment]
I see now that the git-diff is not working as i did a big copy/paste of the whole thing, making it difficult for you to see the changes. Apologies, hope you can figure it out!

**Comment by duracelltomi** [comment]
Thank you very much for your correction. I have to admin, my English needs "some" improvement :-)
I used an online diff tool to see your changes.

Could you revise the text again?

There is one section where I removed some changes: although scroll tracking seems to be now an obsolete feature, the way my plugin can handle this is different from the way GTM implements this.  The solution in my plugin is more content section oriented. GTM's solution is more about the whole page from the very top to the very bottom.

**Comment by henkisdabro** [comment]
Sounds great, I figured that the scroll tracking indeed was better than Google's native one, so thanks for clarifying. I am rather new to github and git in general - please help me out. It seems you have already implemented most of my suggested changes (committed and pushed) into your master branch. How would you prefer that I proceed? Do we close the pull request? Do I commit to the pull request again or do I clone your repo once again and make changes from there? All so confusing, and fun! :-)

**Comment by duracelltomi** [comment]
You have two options:
1) Remove your current fork from your Git account and create it again.
2) Create a new pull request, click on the "compare across forks". After this, you will be able to accept your own pull request, merging my head branch into yours

Anyway, you should use a client to manage your repo and edit files in the repo instead of re-creating them using copy/paste. This will ensure that your changes can be reviewed line by line.

**Comment by henkisdabro** [comment]
Thanks for your assistance. I chose to delete the fork and create a new fork this time. Will look into the form comparison next time too. This is fun.

**Pull request closed without merging**
